

# FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS base
# WORKDIR /app


# FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# ARG BUILD_CONFIGURATION=Release


# Load Dependencies
WORKDIR /src
COPY Chatly.csproj ./
RUN dotnet restore ./Chatly.csproj

# Load Source Code
COPY . .

# # Build Source Code
# RUN dotnet publish ./Chatly.csproj -c Release -o /app/publish



# FROM base AS final
# WORKDIR /app
# COPY --from=build /app/publish .
# ENTRYPOINT ["dotnet",  "Chatly.dll"]
EXPOSE 5280
ENTRYPOINT ["dotnet", "watch", "run"]