// <auto-generated />
using System;
using Chatly.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chatly.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250731045542_InitializeMigration")]
    partial class InitializeMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Chatly.Models.Contact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ActorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<bool>("ChatDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Mutated")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("ContactId");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId", "ContactId")
                        .IsUnique();

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Chatly.Models.ForwardMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PreviousContactId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PreviousSenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SubContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasFilter("[MessageId] IS NOT NULL");

                    b.HasIndex("PreviousContactId");

                    b.HasIndex("PreviousSenderId");

                    b.ToTable("ForwardMessages");
                });

            modelBuilder.Entity("Chatly.Models.Message", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ContactId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsForwarded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReply")
                        .HasColumnType("bit");

                    b.Property<bool>("Read")
                        .HasColumnType("bit");

                    b.Property<string>("SeenAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Chatly.Models.ReplyMessage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PreviousContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviousSenderId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasFilter("[MessageId] IS NOT NULL");

                    b.HasIndex("PreviousSenderId");

                    b.ToTable("ReplyMessages");
                });

            modelBuilder.Entity("Chatly.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Chatly.Models.Contact", b =>
                {
                    b.HasOne("Chatly.Models.User", "Actor")
                        .WithMany("Contacts")
                        .HasForeignKey("ActorId");

                    b.HasOne("Chatly.Models.User", "ContactUser")
                        .WithMany()
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Chatly.Models.Message", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId");

                    b.HasOne("Chatly.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("ContactUser");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Chatly.Models.ForwardMessage", b =>
                {
                    b.HasOne("Chatly.Models.Message", "Message")
                        .WithOne("ForwardMessage")
                        .HasForeignKey("Chatly.Models.ForwardMessage", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Chatly.Models.Contact", "PreviousContact")
                        .WithMany()
                        .HasForeignKey("PreviousContactId");

                    b.HasOne("Chatly.Models.User", "PreviousSender")
                        .WithMany()
                        .HasForeignKey("PreviousSenderId");

                    b.Navigation("Message");

                    b.Navigation("PreviousContact");

                    b.Navigation("PreviousSender");
                });

            modelBuilder.Entity("Chatly.Models.Message", b =>
                {
                    b.HasOne("Chatly.Models.Contact", "Contact")
                        .WithMany("Messages")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Chatly.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.Navigation("Contact");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Chatly.Models.ReplyMessage", b =>
                {
                    b.HasOne("Chatly.Models.Message", "Message")
                        .WithOne("ReplyMessage")
                        .HasForeignKey("Chatly.Models.ReplyMessage", "MessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Chatly.Models.User", "PreviousSender")
                        .WithMany()
                        .HasForeignKey("PreviousSenderId");

                    b.Navigation("Message");

                    b.Navigation("PreviousSender");
                });

            modelBuilder.Entity("Chatly.Models.Contact", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Chatly.Models.Message", b =>
                {
                    b.Navigation("ForwardMessage");

                    b.Navigation("ReplyMessage");
                });

            modelBuilder.Entity("Chatly.Models.User", b =>
                {
                    b.Navigation("Contacts");
                });
#pragma warning restore 612, 618
        }
    }
}
